package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cancelpurchaseauditorie generated by hbm2java
 */
@Entity
@Table(name="cancelpurchaseauditorie"
    ,catalog="storebd"
)
public class Cancelpurchaseauditorie  implements java.io.Serializable {


     private Long canpuraudId;
     private User user;
     private Date canpuraudDate;
     private String purchase;

    public Cancelpurchaseauditorie() {
    }

    public Cancelpurchaseauditorie(User user, Date canpuraudDate, String purchase) {
       this.user = user;
       this.canpuraudDate = canpuraudDate;
       this.purchase = purchase;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="canpuraudId", unique=true, nullable=false)
    public Long getCanpuraudId() {
        return this.canpuraudId;
    }
    
    public void setCanpuraudId(Long canpuraudId) {
        this.canpuraudId = canpuraudId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuId", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="canpuraudDate", nullable=false, length=19)
    public Date getCanpuraudDate() {
        return this.canpuraudDate;
    }
    
    public void setCanpuraudDate(Date canpuraudDate) {
        this.canpuraudDate = canpuraudDate;
    }

    
    @Column(name="purchase", nullable=false)
    public String getPurchase() {
        return this.purchase;
    }
    
    public void setPurchase(String purchase) {
        this.purchase = purchase;
    }




}


