package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cash generated by hbm2java
 */
@Entity
@Table(name="cash"
    ,catalog="storebd"
)
public class Cash  implements java.io.Serializable {


     private Integer cashId;
     private String cashName;
     private String cashIp;
     private int cashPaperSize;
     private String cashPrintName;
     private String cashScalePortSerialName;
     private String cashPrintCommandOpenCashDrawer;

    public Cash() {
    }

    public Cash(String cashName, String cashIp, int cashPaperSize, String cashPrintName, String cashScalePortSerialName, String cashPrintCommandOpenCashDrawer) {
       this.cashName = cashName;
       this.cashIp = cashIp;
       this.cashPaperSize = cashPaperSize;
       this.cashPrintName = cashPrintName;
       this.cashScalePortSerialName = cashScalePortSerialName;
       this.cashPrintCommandOpenCashDrawer = cashPrintCommandOpenCashDrawer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cashId", unique=true, nullable=false)
    public Integer getCashId() {
        return this.cashId;
    }
    
    public void setCashId(Integer cashId) {
        this.cashId = cashId;
    }

    
    @Column(name="cashName", nullable=false, length=100)
    public String getCashName() {
        return this.cashName;
    }
    
    public void setCashName(String cashName) {
        this.cashName = cashName;
    }

    
    @Column(name="cashIP", nullable=false, length=250)
    public String getCashIp() {
        return this.cashIp;
    }
    
    public void setCashIp(String cashIp) {
        this.cashIp = cashIp;
    }

    
    @Column(name="cashPaperSize", nullable=false)
    public int getCashPaperSize() {
        return this.cashPaperSize;
    }
    
    public void setCashPaperSize(int cashPaperSize) {
        this.cashPaperSize = cashPaperSize;
    }

    
    @Column(name="cashPrintName", nullable=false, length=250)
    public String getCashPrintName() {
        return this.cashPrintName;
    }
    
    public void setCashPrintName(String cashPrintName) {
        this.cashPrintName = cashPrintName;
    }

    
    @Column(name="cashScalePortSerialName", nullable=false, length=20)
    public String getCashScalePortSerialName() {
        return this.cashScalePortSerialName;
    }
    
    public void setCashScalePortSerialName(String cashScalePortSerialName) {
        this.cashScalePortSerialName = cashScalePortSerialName;
    }

    
    @Column(name="cashPrintCommandOpenCashDrawer", nullable=false, length=200)
    public String getCashPrintCommandOpenCashDrawer() {
        return this.cashPrintCommandOpenCashDrawer;
    }
    
    public void setCashPrintCommandOpenCashDrawer(String cashPrintCommandOpenCashDrawer) {
        this.cashPrintCommandOpenCashDrawer = cashPrintCommandOpenCashDrawer;
    }




}


