package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupp generated by hbm2java
 */
@Entity
@Table(name="groupp"
    ,catalog="storebd"
)
public class Groupp  implements java.io.Serializable {


     private String grouId;
     private String grouDescription;
     private Set<Usergroup> usergroups = new HashSet<Usergroup>(0);

    public Groupp() {
    }

	
    public Groupp(String grouId) {
        this.grouId = grouId;
    }
    public Groupp(String grouId, String grouDescription, Set<Usergroup> usergroups) {
       this.grouId = grouId;
       this.grouDescription = grouDescription;
       this.usergroups = usergroups;
    }
   
     @Id 

    
    @Column(name="grouId", unique=true, nullable=false, length=20)
    public String getGrouId() {
        return this.grouId;
    }
    
    public void setGrouId(String grouId) {
        this.grouId = grouId;
    }

    
    @Column(name="grouDescription", length=256)
    public String getGrouDescription() {
        return this.grouDescription;
    }
    
    public void setGrouDescription(String grouDescription) {
        this.grouDescription = grouDescription;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groupp")
    public Set<Usergroup> getUsergroups() {
        return this.usergroups;
    }
    
    public void setUsergroups(Set<Usergroup> usergroups) {
        this.usergroups = usergroups;
    }




}


