package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lend generated by hbm2java
 */
@Entity
@Table(name="lend"
    ,catalog="storebd"
)
public class Lend  implements java.io.Serializable {


     private Long lendId;
     private Client client;
     private User user;
     private Date lendDate;
     private int lendValue;
     private Integer lendPayment;
     private int lendState;

    public Lend() {
    }

	
    public Lend(Client client, User user, Date lendDate, int lendValue, int lendState) {
        this.client = client;
        this.user = user;
        this.lendDate = lendDate;
        this.lendValue = lendValue;
        this.lendState = lendState;
    }
    public Lend(Client client, User user, Date lendDate, int lendValue, Integer lendPayment, int lendState) {
       this.client = client;
       this.user = user;
       this.lendDate = lendDate;
       this.lendValue = lendValue;
       this.lendPayment = lendPayment;
       this.lendState = lendState;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lendId", unique=true, nullable=false)
    public Long getLendId() {
        return this.lendId;
    }
    
    public void setLendId(Long lendId) {
        this.lendId = lendId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliId", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usId", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lendDate", nullable=false, length=19)
    public Date getLendDate() {
        return this.lendDate;
    }
    
    public void setLendDate(Date lendDate) {
        this.lendDate = lendDate;
    }

    
    @Column(name="lendValue", nullable=false)
    public int getLendValue() {
        return this.lendValue;
    }
    
    public void setLendValue(int lendValue) {
        this.lendValue = lendValue;
    }

    
    @Column(name="lendPayment")
    public Integer getLendPayment() {
        return this.lendPayment;
    }
    
    public void setLendPayment(Integer lendPayment) {
        this.lendPayment = lendPayment;
    }

    
    @Column(name="lendState", nullable=false)
    public int getLendState() {
        return this.lendState;
    }
    
    public void setLendState(int lendState) {
        this.lendState = lendState;
    }




}


