package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="storebd"
)
public class Orders  implements java.io.Serializable {


     private Long orId;
     private Provider provider;
     private User user;
     private Date orDate;
     private Date orDateReceived;
     private Date orDeliveryDate;
     private int orState;
     private Integer orTotal;
     private Set<Orderitem> orderitems = new HashSet<Orderitem>(0);

    public Orders() {
    }

	
    public Orders(Provider provider, User user, Date orDate, Date orDeliveryDate, int orState) {
        this.provider = provider;
        this.user = user;
        this.orDate = orDate;
        this.orDeliveryDate = orDeliveryDate;
        this.orState = orState;
    }
    public Orders(Provider provider, User user, Date orDate, Date orDateReceived, Date orDeliveryDate, int orState, Integer orTotal, Set<Orderitem> orderitems) {
       this.provider = provider;
       this.user = user;
       this.orDate = orDate;
       this.orDateReceived = orDateReceived;
       this.orDeliveryDate = orDeliveryDate;
       this.orState = orState;
       this.orTotal = orTotal;
       this.orderitems = orderitems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="orId", unique=true, nullable=false)
    public Long getOrId() {
        return this.orId;
    }
    
    public void setOrId(Long orId) {
        this.orId = orId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="provId", nullable=false)
    public Provider getProvider() {
        return this.provider;
    }
    
    public void setProvider(Provider provider) {
        this.provider = provider;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usId", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orDate", nullable=false, length=19)
    public Date getOrDate() {
        return this.orDate;
    }
    
    public void setOrDate(Date orDate) {
        this.orDate = orDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orDateReceived", length=19)
    public Date getOrDateReceived() {
        return this.orDateReceived;
    }
    
    public void setOrDateReceived(Date orDateReceived) {
        this.orDateReceived = orDateReceived;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orDeliveryDate", nullable=false, length=19)
    public Date getOrDeliveryDate() {
        return this.orDeliveryDate;
    }
    
    public void setOrDeliveryDate(Date orDeliveryDate) {
        this.orDeliveryDate = orDeliveryDate;
    }

    
    @Column(name="orState", nullable=false)
    public int getOrState() {
        return this.orState;
    }
    
    public void setOrState(int orState) {
        this.orState = orState;
    }

    
    @Column(name="orTotal")
    public Integer getOrTotal() {
        return this.orTotal;
    }
    
    public void setOrTotal(Integer orTotal) {
        this.orTotal = orTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<Orderitem> getOrderitems() {
        return this.orderitems;
    }
    
    public void setOrderitems(Set<Orderitem> orderitems) {
        this.orderitems = orderitems;
    }




}


