package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orderitem generated by hbm2java
 */
@Entity
@Table(name="orderitem"
    ,catalog="storebd"
)
public class Orderitem  implements java.io.Serializable {


     private Long orItemId;
     private Orders orders;
     private Product product;
     private String orItemProdUnregister;
     private int orItemQuantity;
     private int orItemUnitPrice;

    public Orderitem() {
    }

	
    public Orderitem(Orders orders, int orItemQuantity, int orItemUnitPrice) {
        this.orders = orders;
        this.orItemQuantity = orItemQuantity;
        this.orItemUnitPrice = orItemUnitPrice;
    }
    public Orderitem(Orders orders, Product product, String orItemProdUnregister, int orItemQuantity, int orItemUnitPrice) {
       this.orders = orders;
       this.product = product;
       this.orItemProdUnregister = orItemProdUnregister;
       this.orItemQuantity = orItemQuantity;
       this.orItemUnitPrice = orItemUnitPrice;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="orItemId", unique=true, nullable=false)
    public Long getOrItemId() {
        return this.orItemId;
    }
    
    public void setOrItemId(Long orItemId) {
        this.orItemId = orItemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orId", nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prodId")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="orItemProdUnregister", length=200)
    public String getOrItemProdUnregister() {
        return this.orItemProdUnregister;
    }
    
    public void setOrItemProdUnregister(String orItemProdUnregister) {
        this.orItemProdUnregister = orItemProdUnregister;
    }

    
    @Column(name="orItemQuantity", nullable=false)
    public int getOrItemQuantity() {
        return this.orItemQuantity;
    }
    
    public void setOrItemQuantity(int orItemQuantity) {
        this.orItemQuantity = orItemQuantity;
    }

    
    @Column(name="orItemUnitPrice", nullable=false)
    public int getOrItemUnitPrice() {
        return this.orItemUnitPrice;
    }
    
    public void setOrItemUnitPrice(int orItemUnitPrice) {
        this.orItemUnitPrice = orItemUnitPrice;
    }




}


