package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Owner generated by hbm2java
 */
@Entity
@Table(name="owner"
    ,catalog="storebd"
)
public class Owner  implements java.io.Serializable {


     private Integer ownId;
     private String ownName;
     private String ownDescription;
     private Set<Product> products = new HashSet<Product>(0);
     private Set<Purchasetotal> purchasetotals = new HashSet<Purchasetotal>(0);
     private Set<User> users = new HashSet<User>(0);
     private Set<Purchaseitem> purchaseitems = new HashSet<Purchaseitem>(0);

    public Owner() {
    }

	
    public Owner(String ownName, String ownDescription) {
        this.ownName = ownName;
        this.ownDescription = ownDescription;
    }
    public Owner(String ownName, String ownDescription, Set<Product> products, Set<Purchasetotal> purchasetotals, Set<User> users, Set<Purchaseitem> purchaseitems) {
       this.ownName = ownName;
       this.ownDescription = ownDescription;
       this.products = products;
       this.purchasetotals = purchasetotals;
       this.users = users;
       this.purchaseitems = purchaseitems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ownId", unique=true, nullable=false)
    public Integer getOwnId() {
        return this.ownId;
    }
    
    public void setOwnId(Integer ownId) {
        this.ownId = ownId;
    }

    
    @Column(name="ownName", nullable=false, length=250)
    public String getOwnName() {
        return this.ownName;
    }
    
    public void setOwnName(String ownName) {
        this.ownName = ownName;
    }

    
    @Column(name="ownDescription", nullable=false, length=65535)
    public String getOwnDescription() {
        return this.ownDescription;
    }
    
    public void setOwnDescription(String ownDescription) {
        this.ownDescription = ownDescription;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="owner")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="owner")
    public Set<Purchasetotal> getPurchasetotals() {
        return this.purchasetotals;
    }
    
    public void setPurchasetotals(Set<Purchasetotal> purchasetotals) {
        this.purchasetotals = purchasetotals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="owner")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="owner")
    public Set<Purchaseitem> getPurchaseitems() {
        return this.purchaseitems;
    }
    
    public void setPurchaseitems(Set<Purchaseitem> purchaseitems) {
        this.purchaseitems = purchaseitems;
    }




}


