package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pay generated by hbm2java
 */
@Entity
@Table(name="pay"
    ,catalog="storebd"
)
public class Pay  implements java.io.Serializable {


     private Long payId;
     private Client client;
     private User user;
     private Date payDate;
     private int payValue;

    public Pay() {
    }

    public Pay(Client client, User user, Date payDate, int payValue) {
       this.client = client;
       this.user = user;
       this.payDate = payDate;
       this.payValue = payValue;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="payId", unique=true, nullable=false)
    public Long getPayId() {
        return this.payId;
    }
    
    public void setPayId(Long payId) {
        this.payId = payId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliId", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usId", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="payDate", nullable=false, length=19)
    public Date getPayDate() {
        return this.payDate;
    }
    
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    
    @Column(name="payValue", nullable=false)
    public int getPayValue() {
        return this.payValue;
    }
    
    public void setPayValue(int payValue) {
        this.payValue = payValue;
    }




}


