package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Price generated by hbm2java
 */
@Entity
@Table(name="price"
    ,catalog="storebd"
)
public class Price  implements java.io.Serializable {


     private Long priceId;
     private Product product;
     private int priceValue;
     private Date priceInitialDate;
     private Date priceFinalDate;

    public Price() {
    }

	
    public Price(Product product, int priceValue, Date priceInitialDate) {
        this.product = product;
        this.priceValue = priceValue;
        this.priceInitialDate = priceInitialDate;
    }
    public Price(Product product, int priceValue, Date priceInitialDate, Date priceFinalDate) {
       this.product = product;
       this.priceValue = priceValue;
       this.priceInitialDate = priceInitialDate;
       this.priceFinalDate = priceFinalDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="priceId", unique=true, nullable=false)
    public Long getPriceId() {
        return this.priceId;
    }
    
    public void setPriceId(Long priceId) {
        this.priceId = priceId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prodId", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="priceValue", nullable=false)
    public int getPriceValue() {
        return this.priceValue;
    }
    
    public void setPriceValue(int priceValue) {
        this.priceValue = priceValue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="priceInitialDate", nullable=false, length=19)
    public Date getPriceInitialDate() {
        return this.priceInitialDate;
    }
    
    public void setPriceInitialDate(Date priceInitialDate) {
        this.priceInitialDate = priceInitialDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="priceFinalDate", length=19)
    public Date getPriceFinalDate() {
        return this.priceFinalDate;
    }
    
    public void setPriceFinalDate(Date priceFinalDate) {
        this.priceFinalDate = priceFinalDate;
    }




}


