package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pricepurchase generated by hbm2java
 */
@Entity
@Table(name="pricepurchase"
    ,catalog="storebd"
)
public class Pricepurchase  implements java.io.Serializable {


     private Long pricePurId;
     private Product product;
     private int pricePurValue;
     private Date pricePurInitialDate;
     private Date pricePurFinalDate;

    public Pricepurchase() {
    }

	
    public Pricepurchase(Product product, int pricePurValue, Date pricePurInitialDate) {
        this.product = product;
        this.pricePurValue = pricePurValue;
        this.pricePurInitialDate = pricePurInitialDate;
    }
    public Pricepurchase(Product product, int pricePurValue, Date pricePurInitialDate, Date pricePurFinalDate) {
       this.product = product;
       this.pricePurValue = pricePurValue;
       this.pricePurInitialDate = pricePurInitialDate;
       this.pricePurFinalDate = pricePurFinalDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pricePurId", unique=true, nullable=false)
    public Long getPricePurId() {
        return this.pricePurId;
    }
    
    public void setPricePurId(Long pricePurId) {
        this.pricePurId = pricePurId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prodId", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="pricePurValue", nullable=false)
    public int getPricePurValue() {
        return this.pricePurValue;
    }
    
    public void setPricePurValue(int pricePurValue) {
        this.pricePurValue = pricePurValue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pricePurInitialDate", nullable=false, length=19)
    public Date getPricePurInitialDate() {
        return this.pricePurInitialDate;
    }
    
    public void setPricePurInitialDate(Date pricePurInitialDate) {
        this.pricePurInitialDate = pricePurInitialDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pricePurFinalDate", length=19)
    public Date getPricePurFinalDate() {
        return this.pricePurFinalDate;
    }
    
    public void setPricePurFinalDate(Date pricePurFinalDate) {
        this.pricePurFinalDate = pricePurFinalDate;
    }




}


