package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productimage generated by hbm2java
 */
@Entity
@Table(name="productimage"
    ,catalog="storebd"
)
public class Productimage  implements java.io.Serializable {


     private Long prodimgId;
     private Product product;
     private String prodimgPath;
     private boolean prodimgMain;

    public Productimage() {
    }

	
    public Productimage(Product product, boolean prodimgMain) {
        this.product = product;
        this.prodimgMain = prodimgMain;
    }
    public Productimage(Product product, String prodimgPath, boolean prodimgMain) {
       this.product = product;
       this.prodimgPath = prodimgPath;
       this.prodimgMain = prodimgMain;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="prodimgId", unique=true, nullable=false)
    public Long getProdimgId() {
        return this.prodimgId;
    }
    
    public void setProdimgId(Long prodimgId) {
        this.prodimgId = prodimgId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prodId", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="prodimgPath", length=100)
    public String getProdimgPath() {
        return this.prodimgPath;
    }
    
    public void setProdimgPath(String prodimgPath) {
        this.prodimgPath = prodimgPath;
    }

    
    @Column(name="prodimgMain", nullable=false)
    public boolean isProdimgMain() {
        return this.prodimgMain;
    }
    
    public void setProdimgMain(boolean prodimgMain) {
        this.prodimgMain = prodimgMain;
    }




}


