package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producttype generated by hbm2java
 */
@Entity
@Table(name="producttype"
    ,catalog="storebd"
)
public class Producttype  implements java.io.Serializable {


     private Integer prodtypeId;
     private String prodtypeValue;
     private Set<Product> products = new HashSet<Product>(0);

    public Producttype() {
    }

	
    public Producttype(String prodtypeValue) {
        this.prodtypeValue = prodtypeValue;
    }
    public Producttype(String prodtypeValue, Set<Product> products) {
       this.prodtypeValue = prodtypeValue;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="prodtypeId", unique=true, nullable=false)
    public Integer getProdtypeId() {
        return this.prodtypeId;
    }
    
    public void setProdtypeId(Integer prodtypeId) {
        this.prodtypeId = prodtypeId;
    }

    
    @Column(name="prodtypeValue", nullable=false, length=20)
    public String getProdtypeValue() {
        return this.prodtypeValue;
    }
    
    public void setProdtypeValue(String prodtypeValue) {
        this.prodtypeValue = prodtypeValue;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producttype")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


