package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provider generated by hbm2java
 */
@Entity
@Table(name="provider"
    ,catalog="storebd"
)
public class Provider  implements java.io.Serializable {


     private Long provId;
     private String provName;
     private String provEmployeeName;
     private String provPhones;
     private String provAddress;
     private String provRut;
     private String provNit;
     private String provWeb;
     private Set<Provides> provideses = new HashSet<Provides>(0);
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public Provider() {
    }

	
    public Provider(String provName, String provPhones, String provAddress) {
        this.provName = provName;
        this.provPhones = provPhones;
        this.provAddress = provAddress;
    }
    public Provider(String provName, String provEmployeeName, String provPhones, String provAddress, String provRut, String provNit, String provWeb, Set<Provides> provideses, Set<Orders> orderses) {
       this.provName = provName;
       this.provEmployeeName = provEmployeeName;
       this.provPhones = provPhones;
       this.provAddress = provAddress;
       this.provRut = provRut;
       this.provNit = provNit;
       this.provWeb = provWeb;
       this.provideses = provideses;
       this.orderses = orderses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="provId", unique=true, nullable=false)
    public Long getProvId() {
        return this.provId;
    }
    
    public void setProvId(Long provId) {
        this.provId = provId;
    }

    
    @Column(name="provName", nullable=false, length=100)
    public String getProvName() {
        return this.provName;
    }
    
    public void setProvName(String provName) {
        this.provName = provName;
    }

    
    @Column(name="provEmployeeName", length=200)
    public String getProvEmployeeName() {
        return this.provEmployeeName;
    }
    
    public void setProvEmployeeName(String provEmployeeName) {
        this.provEmployeeName = provEmployeeName;
    }

    
    @Column(name="provPhones", nullable=false, length=200)
    public String getProvPhones() {
        return this.provPhones;
    }
    
    public void setProvPhones(String provPhones) {
        this.provPhones = provPhones;
    }

    
    @Column(name="provAddress", nullable=false, length=200)
    public String getProvAddress() {
        return this.provAddress;
    }
    
    public void setProvAddress(String provAddress) {
        this.provAddress = provAddress;
    }

    
    @Column(name="provRut", length=50)
    public String getProvRut() {
        return this.provRut;
    }
    
    public void setProvRut(String provRut) {
        this.provRut = provRut;
    }

    
    @Column(name="provNit", length=50)
    public String getProvNit() {
        return this.provNit;
    }
    
    public void setProvNit(String provNit) {
        this.provNit = provNit;
    }

    
    @Column(name="provWeb", length=300)
    public String getProvWeb() {
        return this.provWeb;
    }
    
    public void setProvWeb(String provWeb) {
        this.provWeb = provWeb;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provider")
    public Set<Provides> getProvideses() {
        return this.provideses;
    }
    
    public void setProvideses(Set<Provides> provideses) {
        this.provideses = provideses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provider")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


