package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Provides generated by hbm2java
 */
@Entity
@Table(name="provides"
    ,catalog="storebd"
)
public class Provides  implements java.io.Serializable {


     private Long providesId;
     private Product product;
     private Provider provider;
     private Date providesInitialDate;
     private Date providesFinalDate;

    public Provides() {
    }

	
    public Provides(Product product, Provider provider, Date providesInitialDate) {
        this.product = product;
        this.provider = provider;
        this.providesInitialDate = providesInitialDate;
    }
    public Provides(Product product, Provider provider, Date providesInitialDate, Date providesFinalDate) {
       this.product = product;
       this.provider = provider;
       this.providesInitialDate = providesInitialDate;
       this.providesFinalDate = providesFinalDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="providesId", unique=true, nullable=false)
    public Long getProvidesId() {
        return this.providesId;
    }
    
    public void setProvidesId(Long providesId) {
        this.providesId = providesId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prodId", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="provId", nullable=false)
    public Provider getProvider() {
        return this.provider;
    }
    
    public void setProvider(Provider provider) {
        this.provider = provider;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="providesInitialDate", nullable=false, length=19)
    public Date getProvidesInitialDate() {
        return this.providesInitialDate;
    }
    
    public void setProvidesInitialDate(Date providesInitialDate) {
        this.providesInitialDate = providesInitialDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="providesFinalDate", length=19)
    public Date getProvidesFinalDate() {
        return this.providesFinalDate;
    }
    
    public void setProvidesFinalDate(Date providesFinalDate) {
        this.providesFinalDate = providesFinalDate;
    }




}


