package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Purchasetotal generated by hbm2java
 */
@Entity
@Table(name="purchasetotal"
    ,catalog="storebd"
)
public class Purchasetotal  implements java.io.Serializable {


     private Long purToId;
     private Owner owner;
     private Purchase purchase;
     private int purToTotal;
     private int purToGain;
     private float purToIva;

    public Purchasetotal() {
    }

    public Purchasetotal(Owner owner, Purchase purchase, int purToTotal, int purToGain, float purToIva) {
       this.owner = owner;
       this.purchase = purchase;
       this.purToTotal = purToTotal;
       this.purToGain = purToGain;
       this.purToIva = purToIva;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="purToId", unique=true, nullable=false)
    public Long getPurToId() {
        return this.purToId;
    }
    
    public void setPurToId(Long purToId) {
        this.purToId = purToId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ownId", nullable=false)
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="purId", nullable=false)
    public Purchase getPurchase() {
        return this.purchase;
    }
    
    public void setPurchase(Purchase purchase) {
        this.purchase = purchase;
    }

    
    @Column(name="purToTotal", nullable=false)
    public int getPurToTotal() {
        return this.purToTotal;
    }
    
    public void setPurToTotal(int purToTotal) {
        this.purToTotal = purToTotal;
    }

    
    @Column(name="purToGain", nullable=false)
    public int getPurToGain() {
        return this.purToGain;
    }
    
    public void setPurToGain(int purToGain) {
        this.purToGain = purToGain;
    }

    
    @Column(name="purToIva", nullable=false, precision=12, scale=0)
    public float getPurToIva() {
        return this.purToIva;
    }
    
    public void setPurToIva(float purToIva) {
        this.purToIva = purToIva;
    }




}


