package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Purchaseitem generated by hbm2java
 */
@Entity
@Table(name="purchaseitem"
    ,catalog="storebd"
)
public class Purchaseitem  implements java.io.Serializable {


     private Long purItemId;
     private Owner owner;
     private Product product;
     private Purchase purchase;
     private int purItemQuantity;
     private int priceValue;
     private int iva;
     private int pricePurValue;

    public Purchaseitem() {
    }

    public Purchaseitem(Owner owner, Product product, Purchase purchase, int purItemQuantity, int priceValue, int iva, int pricePurValue) {
       this.owner = owner;
       this.product = product;
       this.purchase = purchase;
       this.purItemQuantity = purItemQuantity;
       this.priceValue = priceValue;
       this.iva = iva;
       this.pricePurValue = pricePurValue;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="purItemId", unique=true, nullable=false)
    public Long getPurItemId() {
        return this.purItemId;
    }
    
    public void setPurItemId(Long purItemId) {
        this.purItemId = purItemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ownId", nullable=false)
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prodId", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="purId", nullable=false)
    public Purchase getPurchase() {
        return this.purchase;
    }
    
    public void setPurchase(Purchase purchase) {
        this.purchase = purchase;
    }

    
    @Column(name="purItemQuantity", nullable=false)
    public int getPurItemQuantity() {
        return this.purItemQuantity;
    }
    
    public void setPurItemQuantity(int purItemQuantity) {
        this.purItemQuantity = purItemQuantity;
    }

    
    @Column(name="priceValue", nullable=false)
    public int getPriceValue() {
        return this.priceValue;
    }
    
    public void setPriceValue(int priceValue) {
        this.priceValue = priceValue;
    }

    
    @Column(name="iva", nullable=false)
    public int getIva() {
        return this.iva;
    }
    
    public void setIva(int iva) {
        this.iva = iva;
    }

    
    @Column(name="pricePurValue", nullable=false)
    public int getPricePurValue() {
        return this.pricePurValue;
    }
    
    public void setPricePurValue(int pricePurValue) {
        this.pricePurValue = pricePurValue;
    }




}


