package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unity generated by hbm2java
 */
@Entity
@Table(name="unity"
    ,catalog="storebd"
)
public class Unity  implements java.io.Serializable {


     private Integer uniId;
     private String uniName;
     private String uniAbbreviation;
     private Set<Product> products = new HashSet<Product>(0);

    public Unity() {
    }

	
    public Unity(String uniName, String uniAbbreviation) {
        this.uniName = uniName;
        this.uniAbbreviation = uniAbbreviation;
    }
    public Unity(String uniName, String uniAbbreviation, Set<Product> products) {
       this.uniName = uniName;
       this.uniAbbreviation = uniAbbreviation;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="uniId", unique=true, nullable=false)
    public Integer getUniId() {
        return this.uniId;
    }
    
    public void setUniId(Integer uniId) {
        this.uniId = uniId;
    }

    
    @Column(name="uniName", nullable=false, length=60)
    public String getUniName() {
        return this.uniName;
    }
    
    public void setUniName(String uniName) {
        this.uniName = uniName;
    }

    
    @Column(name="uniAbbreviation", nullable=false, length=5)
    public String getUniAbbreviation() {
        return this.uniAbbreviation;
    }
    
    public void setUniAbbreviation(String uniAbbreviation) {
        this.uniAbbreviation = uniAbbreviation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unity")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


