package entities;
// Generated 9/02/2021 12:32:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usergroup generated by hbm2java
 */
@Entity
@Table(name="usergroup"
    ,catalog="storebd"
)
public class Usergroup  implements java.io.Serializable {


     private Long id;
     private Groupp groupp;
     private User user;
     private String usUserName;

    public Usergroup() {
    }

    public Usergroup(Groupp groupp, User user, String usUserName) {
       this.groupp = groupp;
       this.user = user;
       this.usUserName = usUserName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grouId", nullable=false)
    public Groupp getGroupp() {
        return this.groupp;
    }
    
    public void setGroupp(Groupp groupp) {
        this.groupp = groupp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usId", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="usUserName", nullable=false, length=75)
    public String getUsUserName() {
        return this.usUserName;
    }
    
    public void setUsUserName(String usUserName) {
        this.usUserName = usUserName;
    }




}


